from typing import runtime_checkable, Protocol, Any


@runtime_checkable
class IExperienceRepository(Protocol):
    async def add(self, experience: Any): ...

    async def get(self, experience_id: int): ...

    async def list(self, card_id: int): ...


@runtime_checkable
class IProjectsRepository(Protocol):
    async def add(self, project: Any): ...

    async def get(self, project_id: int): ...

    async def list(self, card_id: int) -> list[Any]: ...


@runtime_checkable
class ISkillsRepository(Protocol):
    async def add(self, skill: Any): ...

    async def get(self, skill_id: int): ...

    async def list(self, card_id: int) -> list: ...


@runtime_checkable
class IUserOccupationRepository(Protocol):
    async def add(self, occupation: Any): ...

    async def get(self, occupation_id: int): ...

    async def list(self, card_id: int) -> list: ...


@runtime_checkable
class IMinioImageStorage(Protocol):
    async def upload(self, file_obj, key: str, content_type: str = "image/jpeg") -> None: ...

    async def get_bytes(self, key: str) -> tuple[bytes, str]: ...

    async def delete(self, key: str) -> None: ...
