from typing import runtime_checkable, Protocol, Any


@runtime_checkable
class ICardRepository(Protocol):
    async def add(self, card: Any): ...

    async def detail(self, card_id: int): ...

    async def card_by_user(self, user_id: int): ...

    async def delete(self, card: Any): ...