"""...

Revision ID: 05611e881ef3
Revises: c1e4f7a2b309
Create Date: 2026-03-19 18:08:03.007937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05611e881ef3'
down_revision: Union[str, Sequence[str], None] = 'c1e4f7a2b309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cards_name'), 'cards', type_='unique')
    op.alter_column('experiences', 'text',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('experiences', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=3000),
               existing_nullable=False)
    op.alter_column('projects', 'text',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=700),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user_occupations', 'page',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('user_occupations', 'description',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_occupations', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=700),
               existing_nullable=False)
    op.alter_column('user_occupations', 'page',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('projects', 'text',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
    op.alter_column('experiences', 'description',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('experiences', 'text',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_cards_name'), 'cards', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
